Bridge.assembly("TicketWebsite", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = [System,TicketWebsite.Shared,System.Collections.Generic,TicketWebsite,TicketWebsite.Views,TicketWebsite.Common];
    $m($n[3].App, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void},{"a":1,"n":"RenderUIEditor","is":true,"t":8,"sn":"RenderUIEditor","rt":$n[0].Void}]}; });
    $m($n[4].ShopPage, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"RenderInBody","t":8,"sn":"RenderInBody","rt":$n[0].Void},{"a":1,"n":"DataContext","t":16,"rt":$n[1].ShopPageModel,"g":{"a":1,"n":"get_DataContext","t":8,"rt":$n[1].ShopPageModel,"fg":"DataContext$1"},"fn":"DataContext$1"},{"a":1,"n":"ProductsContainer","t":16,"rt":$,"g":{"a":1,"n":"get_ProductsContainer","t":8,"rt":$,"fg":"ProductsContainer"},"fn":"ProductsContainer"}]}; });
    $m($n[1].FakeFullModel, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[1].Field, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ProductCardImagePath","is":true,"t":4,"rt":$n[0].String,"sn":"ProductCardImagePath"}]}; });
    $m($n[1].FullModel, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ShopPage","t":16,"rt":$n[1].ShopPageModel,"g":{"a":2,"n":"get_ShopPage","t":8,"rt":$n[1].ShopPageModel,"fg":"ShopPage"},"s":{"a":2,"n":"set_ShopPage","t":8,"p":[$n[1].ShopPageModel],"rt":$n[0].Void,"fs":"ShopPage"},"fn":"ShopPage"},{"a":1,"n":"_shopPage","t":4,"rt":$n[1].ShopPageModel,"sn":"_shopPage"}]}; });
    $m($n[1].ShopPageModel, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ProductCards","t":16,"rt":$n[2].List$1(System.ComponentModel.Bag),"g":{"a":2,"n":"get_ProductCards","t":8,"rt":$n[2].List$1(System.ComponentModel.Bag),"fg":"ProductCards"},"s":{"a":2,"n":"set_ProductCards","t":8,"p":[$n[2].List$1(System.ComponentModel.Bag)],"rt":$n[0].Void,"fs":"ProductCards"},"fn":"ProductCards"},{"a":1,"n":"_productCards","t":4,"rt":$n[2].List$1(System.ComponentModel.Bag),"sn":"_productCards"}]}; });
    $m($n[5].Builder, function () { return {"att":1,"a":2,"m":[{"n":".cctor","t":1,"sn":"ctor","sm":true},{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[5].TemplateComponent, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":2,"n":"InitDOM","t":8,"sn":"InitDOM","rt":$n[0].Void},{"a":2,"n":"Template","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Template","t":8,"rt":$n[0].String,"fg":"Template"},"s":{"a":2,"n":"set_Template","t":8,"p":[$n[0].String],"rt":$n[0].Void,"fs":"Template"},"fn":"Template"}]}; });
});
