Bridge.assembly("TicketWebsite", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = [System,TicketWebsite.Models,TicketWebsite,TicketWebsite.Models.Pages.Shop,TicketWebsite.Models.Pages.Shop.ProductsContainer,System.Windows,System.Collections.Generic,TicketWebsite.Shared,TicketWebsite.Views.Footer,TicketWebsite.Views.SidebarMenu,TicketWebsite.Views.Pages.Shop,TicketWebsite.Views.Pages.Shop.MainContent,TicketWebsite.Views.Pages.Shop.LeftMenu,TicketWebsite.Views.Pages.Shop.ProductsContainer,TicketWebsite.Views.Pages.Shop.ProductsContainerCardItem,TicketWebsite.Views.Pages.Shop.HeaderPart,TicketWebsite.Views.Pages.Contact,TicketWebsite.Views.Pages.PaymentPageBody,TicketWebsite.Views.Controls.PaginationMenu,TicketWebsite.Models.Pages.Shop.LeftMenu,TicketWebsite.Common];
    $m($n[2].App, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"HideSidebar","is":true,"t":8,"sn":"HideSidebar","rt":$n[0].Void},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void},{"a":4,"n":"SiteModel","is":true,"t":16,"rt":$n[1].SiteModel,"g":{"a":4,"n":"get_SiteModel","t":8,"rt":$n[1].SiteModel,"fg":"SiteModel","is":true},"fn":"SiteModel"},{"a":4,"n":"Controller","is":true,"t":4,"rt":$n[2].AppController,"sn":"Controller","ro":true},{"a":4,"n":"Router","is":true,"t":4,"rt":$n[2].Router,"sn":"Router","ro":true}]}; });
    $m($n[2].AppController, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"OnContactClicked","t":8,"sn":"OnContactClicked","rt":$n[0].Void},{"a":2,"n":"OnPaymentClicked","t":8,"sn":"OnPaymentClicked","rt":$n[0].Void},{"a":2,"n":"OnShopClicked","t":8,"sn":"OnShopClicked","rt":$n[0].Void},{"a":1,"n":"MainContentContainer","is":true,"t":16,"rt":$,"g":{"a":1,"n":"get_MainContentContainer","t":8,"rt":$,"fg":"MainContentContainer","is":true},"fn":"MainContentContainer"}]}; });
    $m($n[2].Router, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"v":true,"a":2,"n":"HandleNotifiaction","t":8,"pi":[{"n":"eventName","pt":$n[0].String,"ps":0}],"sn":"HandleNotifiaction","rt":$n[0].Void,"p":[$n[0].String]},{"a":2,"n":"NavigateToShopPage","t":8,"sn":"NavigateToShopPage","rt":$n[0].Void}]}; });
    $m($n[8].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[9].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[10].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"RenderInBody","is":true,"t":8,"pi":[{"n":"model","pt":$n[3].Model,"ps":0}],"sn":"RenderInBody","rt":$n[0].Void,"p":[$n[3].Model]}]}; });
    $m($n[11].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[12].View, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[13].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"OnDataContextChanged","t":8,"sn":"OnDataContextChanged","rt":$n[0].Void},{"a":1,"n":"Model","t":16,"rt":$n[4].Model,"g":{"a":1,"n":"get_Model","t":8,"rt":$n[4].Model,"fg":"Model"},"fn":"Model"}]}; });
    $m($n[14].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[15].View, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[16].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[17].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[18].View, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"CreateSubElements","t":8,"sn":"CreateSubElements","rt":$n[0].Void},{"a":1,"n":"OnActiveNumberChanged","is":true,"t":8,"pi":[{"n":"d","pt":$n[5].DependencyObject,"ps":0},{"n":"e","pt":$n[5].DependencyPropertyChangedEventArgs,"ps":1}],"sn":"OnActiveNumberChanged","rt":$n[0].Void,"p":[$n[5].DependencyObject,$n[5].DependencyPropertyChangedEventArgs]},{"a":1,"n":"OnItemCountChanged","is":true,"t":8,"pi":[{"n":"d","pt":$n[5].DependencyObject,"ps":0},{"n":"e","pt":$n[5].DependencyPropertyChangedEventArgs,"ps":1}],"sn":"OnItemCountChanged","rt":$n[0].Void,"p":[$n[5].DependencyObject,$n[5].DependencyPropertyChangedEventArgs]},{"a":1,"n":"SetActive","t":8,"pi":[{"n":"index","pt":$n[0].Int32,"ps":0}],"sn":"SetActive","rt":$n[0].Void,"p":[$n[0].Int32]},{"a":2,"n":"ActiveNumber","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_ActiveNumber","t":8,"rt":$n[0].Int32,"fg":"ActiveNumber","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_ActiveNumber","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"ActiveNumber"},"fn":"ActiveNumber"},{"a":2,"n":"ItemCount","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_ItemCount","t":8,"rt":$n[0].Int32,"fg":"ItemCount","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_ItemCount","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"ItemCount"},"fn":"ItemCount"},{"a":2,"n":"ActiveNumberProperty","is":true,"t":4,"rt":$n[5].DependencyProperty,"sn":"ActiveNumberProperty","ro":true},{"a":2,"n":"ItemCountProperty","is":true,"t":4,"rt":$n[5].DependencyProperty,"sn":"ItemCountProperty","ro":true},{"a":1,"n":"_numbers","t":4,"rt":$n[6].List$1($),"sn":"_numbers","ro":true}]}; });
    $m($n[7].Labels, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[7].ModelBase, function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Labels","t":16,"rt":$n[7].Labels,"g":{"a":2,"n":"get_Labels","t":8,"rt":$n[7].Labels,"fg":"Labels"},"s":{"a":2,"n":"set_Labels","t":8,"p":[$n[7].Labels],"rt":$n[0].Void,"fs":"Labels"},"fn":"Labels"},{"a":1,"n":"_labels","t":4,"rt":$n[7].Labels,"sn":"_labels"}]}; });
    $m($n[7].Field, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ProductCardImagePath","is":true,"t":4,"rt":$n[0].String,"sn":"ProductCardImagePath"},{"a":2,"n":"Product_Categories","is":true,"t":4,"rt":$n[0].String,"sn":"Product_Categories"}]}; });
    $m($n[1].SiteModel, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ShopPage","t":16,"rt":$n[3].Model,"g":{"a":2,"n":"get_ShopPage","t":8,"rt":$n[3].Model,"fg":"ShopPage"},"s":{"a":2,"n":"set_ShopPage","t":8,"p":[$n[3].Model],"rt":$n[0].Void,"fs":"ShopPage"},"fn":"ShopPage"},{"a":1,"n":"_shopPage","t":4,"rt":$n[3].Model,"sn":"_shopPage"}]}; });
    $m($n[1].SiteModelFake, function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[3].Model, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ProductsContainerModel","t":16,"rt":$n[4].Model,"g":{"a":2,"n":"get_ProductsContainerModel","t":8,"rt":$n[4].Model,"fg":"ProductsContainerModel"},"s":{"a":2,"n":"set_ProductsContainerModel","t":8,"p":[$n[4].Model],"rt":$n[0].Void,"fs":"ProductsContainerModel"},"fn":"ProductsContainerModel"},{"a":1,"n":"_productsContainerModel","t":4,"rt":$n[4].Model,"sn":"_productsContainerModel"}]}; });
    $m($n[19].Model, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; });
    $m($n[4].Model, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"ProductCards","t":16,"rt":$n[6].List$1(System.ComponentModel.Bag),"g":{"a":2,"n":"get_ProductCards","t":8,"rt":$n[6].List$1(System.ComponentModel.Bag),"fg":"ProductCards"},"s":{"a":2,"n":"set_ProductCards","t":8,"p":[$n[6].List$1(System.ComponentModel.Bag)],"rt":$n[0].Void,"fs":"ProductCards"},"fn":"ProductCards"},{"a":1,"n":"_productCards","t":4,"rt":$n[6].List$1(System.ComponentModel.Bag),"sn":"_productCards"}]}; });
    $m($n[20].TypeFinder2, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":2,"n":"FindType","t":8,"pi":[{"n":"tag","pt":$n[0].String,"ps":0}],"sn":"FindType","rt":Function,"p":[$n[0].String]},{"a":1,"n":"SearchInThisAssembly","is":true,"t":8,"pi":[{"n":"tag","pt":$n[0].String,"ps":0}],"sn":"SearchInThisAssembly","rt":Function,"p":[$n[0].String]}]}; });
    $m($n[20].FileService, function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"GetFileContent","is":true,"t":8,"pi":[{"n":"fileName","pt":$n[0].String,"ps":0}],"sn":"GetFileContent","rt":$n[0].String,"p":[$n[0].String]}]}; });
    $m($n[20].TemplateComponent, function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"ov":true,"a":2,"n":"InitDOM","t":8,"sn":"InitDOM","rt":$n[0].Void},{"v":true,"a":2,"n":"Notify","t":8,"pi":[{"n":"eventName","pt":$n[0].String,"ps":0}],"sn":"Notify","rt":$n[0].Void,"p":[$n[0].String]},{"a":2,"n":"Template","t":16,"rt":$n[0].String,"g":{"a":2,"n":"get_Template","t":8,"rt":$n[0].String,"fg":"Template"},"s":{"a":2,"n":"set_Template","t":8,"p":[$n[0].String],"rt":$n[0].Void,"fs":"Template"},"fn":"Template"}]}; });
});
